config/routes.rb
Mongodb::Application.routes.draw do
  match 'clients/update_counties_and_cities' => 'clients#update_counties_and_cities', :as => :update_clients_counties_and_cities
  resources :clients
  resources :carrierwave_clients
  resources :paperclip_clients

  root :to => 'clients#index'

end

app/models/client.rb
class Client
  include Mongoid::Document
  # Fields declaration
  field :avatar, :type => String
  field :id_number, :type => String
  field :first_name, :type => String
  field :last_name, :type => String
  field :birthday, :type => Date
  field :use_carrierwave, :type => Boolean, :default => true
  # Associations
  referenced_in :id_type
  referenced_in :gender
  referenced_in :country
  referenced_in :county
  referenced_in :city
  # Validations
  validates_presence_of :id_type_id, :id_number, :first_name, :country_id, :county_id, :city_id
  validates_uniqueness_of :id_number
  
  #------------------------------------------------------------------
  # Returns the full name of the client.
  #------------------------------------------------------------------
  def full_name
    return( "#{self.first_name} #{self.last_name}".strip )
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.xml
  def index
    list
  end
  
  # GET /menus
  # GET /menus.xml
  def list
    @clients = if ( params[:search].blank? )
      Client.all
    else
      conditions = [ {:first_name => /#{params[:search]}/}, {:last_name => /#{params[:search]}/} ]
      Client.any_of(conditions)
    end

    respond_to do |format|
      format.html { render :list }# index.html.erb
      format.js { render :list }
      format.xml  { render :xml => @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.xml
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.xml
  def new
    redirect_to({:controller => 'carrierwave_clients', :action => 'new'})
    return
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.xml
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to(@client, :notice => 'Client was successfully created.') }
        format.xml  { render :xml => @client, :status => :created, :location => @client }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.xml
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to(@client, :notice => 'Client was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.xml
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to(clients_url) }
      format.xml  { head :ok }
    end
  end
  
  # GET the filtered counties or cities to be displayed in the drop down lists.
  def update_counties_and_cities
    unless ( params[:get].blank? || params[:val].blank? )
      if ( params[:get].to_s == 'counties' )
        @items = Country.find(params[:val]).counties
      elsif( params[:get].to_s == 'cities' )
        @items = County.find(params[:val]).cities
      end
    end
    
    response = []
    
    unless ( @items.blank? )
      for item in @items do
        response << {:When => params[:val], :Value => item.id, :Text => item.name}
      end
    end
    
    render({:json => response, :layout => false})
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.haml
- if ( client.use_carrierwave )
  - the_edit_client_path = edit_carrierwave_client_path(client)
- else
  - the_edit_client_path = edit_paperclip_client_path(client)
%tr{ :class => cycle( :odd, :even ) }
  - if ( client.avatar? )
    %td
      - if ( client.use_carrierwave )
        %a{ :href => client.avatar_url, :rel => 'lightbox', :title => client.full_name }
          = image_tag( client.avatar_url( :thumb ) )
        %span{ :style => 'color:blue;' }
          Carrierwave
      - else
        %a{ :href => client.avatar.url, :rel => 'lightbox', :title => client.full_name }
          = image_tag( client.avatar.url( :thumb ) )
        %span{ :style => 'color:red;' }
          Paperclip
  - else
    %td
  %td= client.id_type.name
  %td= client.id_number
  %td= client.first_name
  %td= client.last_name
  %td= client.birthday
  %td= client.gender.name
  %td= client.country.name
  %td= client.county.name
  %td= client.city.name
  %td.action= link_to( t('show'), client )
  %td.action= link_to( t('edit'), the_edit_client_path )
  %td.action= link_to( t('destroy'), client, :confirm => t('are_you_sure'), :method => :delete )

app/views/clients/_form.html.haml
- unless ( @id_types )
  - @id_types = IdType.all.order_by(:name.asc)
- unless ( @genders )
  - @genders = Gender.all.order_by(:name.asc)
- unless ( @countries )
  - @countries = Country.all.order_by(:name.asc)
- unless ( @counties )
  - if ( @client.country.instance_of?(Country) rescue false )
    - @counties = @client.country.counties
  - else
    - @counties = []
- unless ( @cities )
  - if ( @client.county.instance_of?(County) rescue false )
    - @cities = @client.county.cities
  - else
    - @cities = []
= form_for( @client, { :html => { :multipart => true } } ) do |f|
  - if ( @client.errors.any? )
    #errorExplanation
      %h2= "#{pluralize(@client.errors.count, 'error')} prohibited this user from being saved:"
      %ul
      - @client.errors.full_messages.each do |msg|
        %li= msg
  .field
    = f.label( :avatar, 'Avatar' )
    %br
    - if ( @client.avatar? )
      - if ( controller_name == 'paperclip_clients' )
        %a{ :href => @client.avatar.url, :rel => 'lightbox', :title => @client.full_name }
          = image_tag( @client.avatar.url( :thumb ) )
      - else
        %a{ :href => @client.avatar_url, :rel => 'lightbox', :title => @client.full_name }
          = image_tag( @client.avatar_url( :thumb ) )
        = f.check_box( :remove_avatar ) + ' ' + t('.remove_avatar')
      %br
    = f.file_field( :avatar )
    - unless ( controller_name == 'paperclip_clients' )
      = f.hidden_field( :avatar_cache )
  - unless ( controller_name == 'paperclip_clients' )
    .field
      = f.label( :remote_avatar_url, 'or Avatar URL' )
      %br
      = f.text_field( :remote_avatar_url )
  .field
    = f.label( :id_type_id, t('.id_type') )
    %br
    = f.select( :id_type_id, @id_types.collect { |c| [c.name, c.id] }, { :include_blank => t('blank_option') } )
  .field
    = f.label( :id_number, t('.id_number') )
    %br
    = f.text_field( :id_number )
  .field
    = f.label( :first_name, t('.first_name') )
    %br
    = f.text_field( :first_name )
  .field
    = f.label( :last_name, t('.last_name') )
    %br
    = f.text_field( :last_name )
  .field
    = f.label( :birthday, t('.birthday') )
    %br
    = f.date_select( :birthday, { :start_year => 1980, :end_year => 2011, :order => [ :day, :month, :year ], :include_blank => t('blank_option') } )
  .field
    = f.label( :gender_id, t('.gender') )
    %br
    = f.select( :gender_id, @genders.collect { |c| [c.name, c.id] }, { :include_blank => t('blank_option') } )
  .field
    = f.label( :country_id, t('.country') )
    %br
    = f.select( :country_id, @countries.collect { |c| [c.name, c.id] }, { :include_blank => t('blank_option') } )
  .field
    = f.label( :county_id, t('.county') )
    %br
    = f.select( :county_id, @counties.collect { |c| [c.name, c.id] }, { :include_blank => t('blank_option') }, { :disabled => ( @counties.blank? ) } )
  .field
    = f.label( :city_id, t('.city') )
    %br
    = f.select( :city_id, @cities.collect { |c| [c.name, c.id] }, { :include_blank => t('blank_option') }, { :disabled => ( @cities.blank? ) } )
  .actions
    = f.submit
- content_for(:bottom) do
  = javascript_include_tag('jquery/jquery.cascade.js')
  = javascript_include_tag('jquery/jquery.cascade.ext.js')
  = javascript_include_tag('jquery/jquery.templating.js')
- content_for(:document_ready) do
  - if ( controller_name == 'carrierwave_clients' )
    - client_country_id = 'carrierwave_client_country_id'
    - client_county_id = 'carrierwave_client_county_id'
    - client_city_id = 'carrierwave_client_city_id'
  - elsif ( controller_name == 'paperclip_clients' )
    - client_country_id = 'paperclip_client_country_id'
    - client_county_id = 'paperclip_client_county_id'
    - client_city_id = 'paperclip_client_city_id'
  - else
    - client_country_id = 'client_country_id'
    - client_county_id = 'client_county_id'
    - client_city_id = 'client_city_id'
  :erb
    jQuery('#<%= client_county_id %>').cascade('#<%= client_country_id %>', {
      ajax : {
        url : '<%= update_clients_counties_and_cities_path %>',
        data : {
          get : 'counties'
        }
      },
      template : commonTemplate,
      match : commonMatch
    }).bind('loaded.cascade', function( e, target ) {
      var jThis = jQuery(this);
      
      if ( jThis.html() == '' ) { jThis.attr('disabled', 'disabled'); }
      jThis.prepend('<option value="" selected="selected"><%= t('blank_option') %></option>');
      jThis.find("option:first")[0].selected = true;
    });
    
    jQuery('#<%= client_city_id %>').cascade('#<%= client_county_id %>', {
      ajax : {
        url : '<%= update_clients_counties_and_cities_path %>',
        data : {
          get : 'cities'
        }
      },
      template : commonTemplate,
      match : commonMatch
    }).bind('loaded.cascade', function( e, target ) {
      var jThis = jQuery(this);
      
      if ( jThis.html() == '' ) { jThis.attr('disabled', 'disabled'); }
      jThis.prepend('<option value="" selected="selected"><%= t('blank_option') %></option>');
      jThis.find("option:first")[0].selected = true;
    });

app/views/clients/edit.html.haml
- content_for(:head_title) do
  = t('.title')
- if ( controller_name == 'carrierwave_clients' )
  - the_clients_path = carrierwave_clients_path
- elsif ( controller_name == 'paperclip_clients' )
  - the_clients_path = paperclip_clients_path
- else
  - the_clients_path = clients_path
%h1= t('.title')
%p
  = link_to( t('back'), the_clients_path ) + '|'
  = link_to( t('show'), @client )
= render({:partial => 'clients/form'})

app/views/clients/list.html.haml
- content_for(:head_title) do
  = t('.title')
- if ( controller_name == 'carrierwave_clients' )
  - the_new_client_path = new_carrierwave_client_path
  - the_clients_path = carrierwave_clients_path
- elsif ( controller_name == 'paperclip_clients' )
  - the_new_client_path = new_paperclip_client_path
  - the_clients_path = paperclip_clients_path
- else
  - the_new_client_path = new_client_path
  - the_clients_path = clients_path
%h1= t('.title')
%p= link_to( t('.new_client'), the_new_client_path )
= form_tag( the_clients_path, { :method => :get, :remote => true } ) do
  .field
    = label_tag( t('search') )
    = search_field_tag( :search, params[:search] )
    = submit_tag( t('search') )
%table
  %thead
    %tr
      %th= Client.human_attribute_name :avatar
      %th= Client.human_attribute_name :identification_type
      %th= Client.human_attribute_name :id_number
      %th= Client.human_attribute_name :first_name
      %th= Client.human_attribute_name :last_name
      %th= Client.human_attribute_name :birthday
      %th= Client.human_attribute_name :gender
      %th= Client.human_attribute_name :country
      %th= Client.human_attribute_name :county
      %th= Client.human_attribute_name :city
      %th{:colspan => 3}= t('actions')
  %tbody#clients.list
    - if ( @clients.size > 0 )
      = render({:partial => 'clients/client', :collection => @clients})
    - else
      %tr
        %td{ :colspan => 10 }= t('.empty')

app/views/clients/list.js.erb
<%- if ( @clients.blank? ) -%>
  jQuery('#clients').html('<td colspan="10"><%= t('.empty') %> for : "<%= params[:search] %>"</td>');
<%- else -%>
  jQuery('#clients').html('<%= escape_javascript(render({:partial => 'clients/client', :collection => @clients})) %>');
<%- end -%>

app/views/clients/new.html.haml
- content_for(:head_title) do
  = t('.title')
- if ( controller_name == 'carrierwave_clients' )
  - the_clients_path = carrierwave_clients_path
- elsif ( controller_name == 'paperclip_clients' )
  - the_clients_path = paperclip_clients_path
- else
  - the_clients_path = clients_path
%h1= t('.title')
%p= link_to(t('back'), the_clients_path)
= render({:partial => 'clients/form'})

app/views/clients/show.html.haml
- content_for(:head_title) do
  = t('.title')
%h1= t '.title'
- if ( controller_name == 'carrierwave_clients' )
  - the_clients_path = carrierwave_clients_path
  - the_edit_client_path = edit_carrierwave_client_path(@client)
- elsif ( controller_name == 'paperclip_clients' )
  - the_clients_path = paperclip_clients_path
  - the_edit_client_path = edit_paperclip_client_path(@client)
- else
  - the_clients_path = clients_path
  - the_edit_client_path = edit_carrierwave_client_path(@client)
%p
  = link_to( t('back'), the_clients_path ) + '|'
  = link_to( t('edit'), the_edit_client_path ) + '|'
  = link_to( t('destroy'), @client, :confirm => t('are_you_sure'), :method => :delete )
%dl
  - if ( @client.avatar? )
    %dt= 'Avatar'
    %dd
      - if ( controller_name == 'paperclip_clients' )
        %a{ :href => @client.avatar.url, :rel => 'lightbox', :title => @client.full_name }
          = image_tag( @client.avatar.url( :main ) )
      - else
        %a{ :href => @client.avatar_url, :rel => 'lightbox', :title => @client.full_name }
          = image_tag( @client.avatar_url( :main ) )
  %dt= Client.human_attribute_name :identification_number
  %dd= @client.id_type.name
  %dt= Client.human_attribute_name :id_number
  %dd= @client.id_number
  %dt= Client.human_attribute_name :first_name
  %dd= @client.first_name
  %dt= Client.human_attribute_name :last_name
  %dd= @client.last_name
  %dt= Client.human_attribute_name :birthday
  %dd= @client.birthday
  %dt= Client.human_attribute_name :gender
  %dd= @client.gender.name
  %dt= Client.human_attribute_name :country
  %dd= @client.country.name
  %dt= Client.human_attribute_name :county
  %dd= @client.county.name
  %dt= Client.human_attribute_name :city
  %dd= @client.city.name